assets:
  - dev.sql.gz
steps:
  - name: Update Composer
    command: '/usr/local/bin/composer self-update'
  - name: Get proper drush version
    command: 'composer global require drush/drush:dev-master ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Probo site setup
    plugin: Drupal
    database: dev.sql.gz
    databaseGzipped: true
    databaseUpdates: false
    clearCaches: false
  - name: Append site-settings.php
    command: "echo \"require_once('sites/default/site-settings.php');\" >> /var/www/html/sites/default/settings.php"
  - name: Earlier cache clear
    command: "drush --root='/var/www/html/' cr"
  - name: Import configuration
    command: "sleep 3 ; drush --root='/var/www/html/' config-import --source='/var/www/html/sites/default/config/sync' -y"
  - name: Database Updates
    command: "drush --root='/var/www/html/' updb -y"
  - name: Rebuild caches
    command: "drush --root='/var/www/html/' cache-rebuild"
  - name: Generate login link
    command: "drush --root='/var/www/html/' uli"