<?php

/**
 * @file
 * Contains taxonomy_department.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function taxonomy_department_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_department module.
    case 'help.page.taxonomy_department':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Keeping all of PennLibs taxonomies in code for deployment.') . '</p>';
      return $output;

    default:
  }
}
