<?php

/**
 * @file
 * Contains pennlib_taxonomy.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pennlib_taxonomy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pennlib_taxonomy module.
    case 'help.page.pennlib_taxonomy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is designed to deploy all of PennLibs taxonomies in code
      rather than manually entering in content into each staging environments database.') . '</p>';
      return $output;

    default:
  }
}
