definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  standard__front_page:
    weight: -50
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -48
  user__logout:
    menu_name: account
    parent: ''
    weight: 10
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
